### PR TITLE
Feature/database

### PR DESCRIPTION
**Pull request by Bahia-Nascimento**
Initial querries already implemented, we may want to refactor afterwards to reformat the returns.
TODO:  couldn't yet implement the "compare" and "medals/continent" querries since we lack information on the database

### CODE REVIEW

**Review by JevsJevs — APPROVED** [review]

**Review by JevsJevs — CHANGES_REQUESTED** [review]
The nature of the changes are fine. Just check the pending conflict and you're gtg

**Comment by JevsJevs** [comment]
As of now the tests break is being caused by wrong DB path name. The test execution seems to be not resolving the relative DB path correctly. The fix is to set the path using OS based functions

**Comment by JevsJevs** [comment]
@Bahia-Nascimento,  Made some changes, could you review them? Can't request it through github somehow.

**Comment by Bahia-Nascimento** [comment]
looks good, ready to merge

**Pull request merged**
