### PR TITLE
Provisory Chart Api

### LINKED ISSUE #6: Create a api to get chart data
Create a get endpoint to retrieve data from our provisory csv file (DB mockup)

### PR DESCRIPTION
**Pull request by mat-andrade**
Temporary implementation of the _/medals_ endpoint exposing the data in the current csv file used as a database.

### CODE REVIEW

**Review by JevsJevs — CHANGES_REQUESTED** [review]
Please link the issue with the commit using #6. As this is a one feature/one developer branch its acceptable to force-push an altered local branch

**Comment by mat-andrade** [comment]
> Please link the issue with the commit using #6. As this is a one feature/one developer branch its acceptable to force-push an altered local branch

Done.

**Review by Bahia-Nascimento — APPROVED** [review]
Looks good to me

**Review by brenonishimoto — APPROVED** [review]

**Review by JevsJevs — APPROVED** [review]
NIce PR

**Pull request merged**
